Stage C Codes

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, RandomizedSearchCV, KFold, StratifiedKFold, LeaveOneOut
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix, classification_report
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb

In [2]:
df = pd.read_csv('Data_for_UCI_named.csv')

In [3]:
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [4]:
df.dtypes

tau1     float64
tau2     float64
tau3     float64
tau4     float64
p1       float64
p2       float64
p3       float64
p4       float64
g1       float64
g2       float64
g3       float64
g4       float64
stab     float64
stabf     object
dtype: object

In [5]:
df.isna().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [6]:
df = df.drop(columns=['stab'])
x = df.drop(columns=['stabf'])
y = df['stabf']
df

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1     9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2     8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3     0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4     3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...        ...       ...       ...       ...       ...       ...       ...   
9995  2.930406  9.487627  2.376523  6.187797  3.343416 -0.658054 -1.449106   
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437   
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884   
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915   
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193   

            p4        g1        g2        g3        g4     stabf  
0    -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1    -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2    -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3    -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4    -0.554305  0.797110  0.455450  0.656947  0.820923  unstable  
...        ...       ...       ...       ...       ...       ...  
9995 -1.236256  0.601709  0.779642  0.813512  0.608385  unstable  
9996 -1.733414  0.502079  0.567242  0.285880  0.366120    stable  
9997 -1.975373  0.487838  0.986505  0.149286  0.145984    stable  
9998 -0.898510  0.365246  0.587558  0.889118  0.818391  unstable  
9999 -0.570329  0.073056  0.505441  0.378761  0.942631  unstable  

[10000 rows x 13 columns]

In [7]:
le=LabelEncoder()
df.iloc[:,-1]= le.fit_transform(df.iloc[:,-1])
y = df['stabf']
y

0       1
1       0
2       1
3       1
4       1
       ..
9995    1
9996    0
9997    0
9998    1
9999    1
Name: stabf, Length: 10000, dtype: int32

In [8]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
y_train.value_counts()

1    5092
0    2908
Name: stabf, dtype: int64

In [9]:
x_train
x_test

tau1      tau2      tau3      tau4        p1        p2        p3  \
9953  6.877876  4.113820  9.356768  8.299753  4.056779 -1.897470 -1.590581   
3850  5.802841  6.271371  4.731540  3.819867  3.579569 -1.709480 -1.067511   
4962  2.286998  4.385142  2.830232  5.293880  3.035814 -1.202764 -0.902011   
3886  5.019920  2.209962  6.266080  0.578901  4.322584 -1.960207 -1.074561   
5437  7.646145  9.187896  5.484219  9.934313  3.634226 -1.254541 -1.335366   
...        ...       ...       ...       ...       ...       ...       ...   
3919  8.320531  3.394352  1.468729  8.766874  3.940123 -1.599081 -0.931023   
162   2.290102  3.028512  8.071234  6.169944  3.624592 -1.104003 -0.820951   
7903  7.848945  0.684889  0.728223  6.702948  2.599685 -0.563497 -1.210069   
2242  2.173967  5.776797  4.597638  6.399330  2.869349 -0.931891 -1.237955   
2745  1.467618  9.389085  6.019740  9.376247  4.242404 -1.894794 -1.589085   

            p4        g1        g2        g3        g4  
9953 -0.568728  0.276567  0.845536  0.112440  0.822562  
3850 -0.802579  0.077527  0.416478  0.912846  0.861306  
4962 -0.931039  0.924216  0.130186  0.703887  0.063811  
3886 -1.287815  0.546910  0.065992  0.427349  0.814648  
5437 -1.044319  0.561528  0.121611  0.787318  0.300314  
...        ...       ...       ...       ...       ...  
3919 -1.410020  0.657445  0.493384  0.178907  0.173240  
162  -1.699638  0.785595  0.770194  0.234290  0.225070  
7903 -0.826119  0.185122  0.559799  0.682418  0.886902  
2242 -0.699503  0.942680  0.743103  0.152161  0.305183  
2745 -0.758525  0.659519  0.273217  0.526145  0.851163  

[2000 rows x 12 columns]

In [10]:
y.unique()

array([1, 0])

In [11]:
y_train

2694    1
5140    1
2568    1
3671    1
7427    1
       ..
2895    0
7813    0
905     1
5192    1
235     0
Name: stabf, Length: 8000, dtype: int32

In [12]:
scaler = StandardScaler()
normalised_train_df = pd.DataFrame(scaler.fit_transform(x_train), columns=x_train.columns)
normalised_test_df = pd.DataFrame(scaler.fit_transform(x_test), columns=x_test.columns)

In [13]:
normalised_train_df

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     0.367327 -0.986042  0.650447  1.547527 -0.291490  0.061535  1.293862   
1    -0.064659  0.089437  1.035079 -1.641494  0.619865 -0.067235 -1.502925   
2    -1.467850  1.298418 -0.502536  1.166046 -0.180521  0.490603  0.682560   
3     0.820081  0.529920  1.299657 -1.141975 -0.812854 -0.763632  1.521579   
4     0.665424 -1.425627  0.312300  0.919137 -1.614296  0.760315  1.422019   
...        ...       ...       ...       ...       ...       ...       ...   
7995  1.551314  0.007408 -1.177640  1.016898 -0.397177  0.759820 -0.636951   
7996  1.015925 -0.223483 -1.489381 -1.479078  0.451468 -0.731994  0.990355   
7997  0.657609 -0.722756 -1.405888 -0.274301 -0.012584  1.438694 -0.364266   
7998 -0.059316 -1.260532 -1.010471 -0.877808 -0.779769  0.828824  0.516923   
7999 -1.473214  0.638438  0.250122 -0.996484  1.950944 -1.163800 -0.732842   

            p4        g1        g2        g3        g4  
0    -0.845074  0.160918  0.339859  0.585568  0.492239  
1     0.486613 -0.293143 -1.558488  1.429649 -1.443521  
2    -0.855302  1.399350  1.451534 -1.045743  0.492489  
3     0.658780 -0.958319  1.361958  1.604140  0.275303  
4     0.639243  1.676895  0.695660  1.137504 -1.312575  
...        ...       ...       ...       ...       ...  
7995  0.572703 -1.209413  0.313976 -1.625728 -0.637401  
7996 -1.048148 -1.094647 -0.755209  0.734821 -0.304433  
7997 -1.046683  1.253539  0.293100 -1.550587  0.810344  
7998  0.018984 -0.182448 -0.388255 -0.726781  1.667916  
7999 -1.513302  1.230438 -1.174110  1.179282  0.783627  

[8000 rows x 12 columns]

In [14]:
normalised_test_df

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     0.592163 -0.420565  1.472472  1.093036  0.426786 -1.504594 -0.792677   
1     0.199183  0.364543 -0.190076 -0.518473 -0.229402 -1.071766  0.427103   
2    -1.086035 -0.321834 -0.873505  0.011761 -0.977094  0.094896  0.813041   
3    -0.087014 -1.113357  0.361518 -1.684316  0.792280 -1.649041  0.410662   
4     0.873004  1.425833  0.080476  1.681022 -0.154247 -0.024315 -0.197525   
...        ...       ...       ...       ...       ...       ...       ...   
1995  1.119526 -0.682371 -1.362900  1.261070  0.266377 -0.817583  0.745388   
1996 -1.084900 -0.815496  1.010385  0.326900 -0.167494  0.322284  1.002069   
1997  0.947138 -1.668313 -1.629077  0.518632 -1.576793  1.566742  0.094662   
1998 -1.127354  0.184573 -0.238207  0.409415 -1.205991  0.718553  0.029632   
1999 -1.385560  1.499043  0.272971  1.480274  0.682028 -1.498433 -0.789188   

            p4        g1        g2        g3        g4  
0     1.600201 -0.925703  1.175287 -1.492644  1.086291  
1     1.052337 -1.655910 -0.395949  1.412703  1.227535  
2     0.751381  1.450284 -1.444370  0.654216 -1.679799  
3    -0.084473  0.066085 -1.679450 -0.349573  1.057439  
4     0.485988  0.119716 -1.475773  0.957057 -0.817608  
...        ...       ...       ...       ...       ...  
1995 -0.370774  0.471600 -0.114316 -1.251379 -1.280864  
1996 -1.049289  0.941736  0.899379 -1.050349 -1.091915  
1997  0.997188 -1.261183  0.128899  0.576286  1.320848  
1998  1.293823  1.518021  0.800172 -1.348463 -0.799858  
1999  1.155547  0.479208 -0.920581  0.009039  1.190559  

[2000 rows x 12 columns]

In [15]:
rf_classifier = RandomForestClassifier(random_state = 1)
rf_classifier.fit(normalised_train_df, y_train)
rf_classifier


RandomForestClassifier(random_state=1)

In [16]:
prediction = rf_classifier.predict(normalised_test_df)
prediction

array([1, 1, 0, ..., 0, 0, 1])

In [17]:
cfm_rf = confusion_matrix(prediction, y_test)
cfm_rf

array([[ 624,   56],
       [  88, 1232]], dtype=int64)

In [18]:
accuracy_rf = accuracy_score(prediction, y_test)
accuracy_rf

0.928

In [19]:
rd = round(accuracy_rf,4)
rd

0.928

In [20]:
from sklearn.ensemble import ExtraTreesClassifier

In [21]:
etc = ExtraTreesClassifier(random_state=1)
etc.fit(normalised_train_df, y_train)

ExtraTreesClassifier(random_state=1)

In [22]:
pred_etc = etc.predict(normalised_test_df)
accuracy_etc = accuracy_score(pred_etc, y_test)
cfm_etc = confusion_matrix(pred_etc, y_test)
accuracy_etc
cfm_etc

array([[ 602,   38],
       [ 110, 1250]], dtype=int64)

In [23]:
accuracy_etc

0.926

In [24]:
clf_xgb = xgb.XGBClassifier(random_state=1)
clf_xgb.fit(normalised_train_df, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, feature_types=None, gamma=0, gpu_id=-1,
              grow_policy='depthwise', importance_type=None,
              interaction_constraints='', learning_rate=0.300000012,
              max_bin=256, max_cat_threshold=64, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=6, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, predictor='auto', random_state=1, ...)

In [25]:
 xg_pred = clf_xgb.predict(normalised_test_df)

In [26]:
accuracy_xg = accuracy_score(xg_pred, y_test)
accuracy_xg

0.946

In [27]:
cfm_xg = confusion_matrix(xg_pred, y_test)
cfm_xg

array([[ 647,   43],
       [  65, 1245]], dtype=int64)

In [28]:
import lightgbm as lgb

In [29]:
clf_lgb = lgb.LGBMClassifier(random_state=1)

In [30]:
clf_lgb.fit(normalised_train_df, y_train)

LGBMClassifier(random_state=1)

In [31]:
lgb_predict = clf_lgb.predict(normalised_test_df)

In [32]:
accuracy_lgb = accuracy_score(lgb_predict, y_test)
accuracy_lgb

0.9365

In [33]:
cfm_lgb = confusion_matrix(lgb_predict, y_test)
cfm_lgb

array([[ 636,   51],
       [  76, 1237]], dtype=int64)

In [34]:
random_grid = {'n_estimator':200, 'min_samples_split': 5, 'max_features': 'auto'}

In [35]:
clf_lgb = lgb.LGBMClassifier(random_state=1)
clf_lgb_randomcv=RandomizedSearchCV(estimator=clf_lgb, cv=5, param_distributions=random_grid, n_iter=10, scoring = 'accuracy', n_jobs = -1, verbose = 1,random_state = 1)